[package]
authors = ["Xuanwo <github@xuanwo.io>"]
categories = ["command-line-utilities"]
description = "Layered configuration system built upon serde"
documentation = "https://docs.rs/serde-env"
repository = "https://github.com/Xuanwo/serde-env"
edition = "2021"
license = "Apache-2.0"
name = "serde-env"
version = "0.0.0"

[dependencies]
